package demo

const ProjectREADME = `# Grafana Dashboard Linter Demo

This directory was generated by gdlint init.

## Included Files

- dashboards/good-dashboard.json: a small dashboard with a stable UID, tags, datasource variable, query, and unit.
- dashboards/bad-dashboard.json: a valid dashboard with intentional lint issues such as duplicate panel IDs, empty queries, missing datasource, aggressive refresh, and broad queries.

## Run The Linter

From this directory:

` + "```sh" + `
gdlint check --dir dashboards
gdlint check --dir dashboards --format markdown --output report.md
gdlint check --dir dashboards --fail-on-risk high
gdlint check --dir dashboards --strict
` + "```" + `

## Customize

Replace the sample JSON files with exported Grafana dashboards or add your own dashboards under dashboards/.
`

const GoodDashboard = `{
  "uid": "k8s-overview",
  "title": "Kubernetes Overview",
  "description": "Cluster health and workload overview.",
  "tags": ["kubernetes", "platform"],
  "schemaVersion": 39,
  "refresh": "30s",
  "templating": {
    "list": [
      {
        "name": "namespace",
        "type": "query",
        "datasource": {
          "type": "prometheus",
          "uid": "${DS_PROMETHEUS}"
        },
        "query": "label_values(kube_pod_info, namespace)",
        "regex": ""
      }
    ]
  },
  "panels": [
    {
      "id": 1,
      "title": "CPU Usage",
      "description": "CPU usage by namespace.",
      "type": "timeseries",
      "datasource": {
        "type": "prometheus",
        "uid": "${DS_PROMETHEUS}"
      },
      "fieldConfig": {
        "defaults": {
          "unit": "percent"
        }
      },
      "targets": [
        {
          "refId": "A",
          "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container!=\"\"}[5m])) by (namespace)",
          "interval": "30s"
        }
      ]
    }
  ]
}
`

const BadDashboard = `{
  "title": "Problematic Kubernetes Dashboard",
  "tags": [],
  "schemaVersion": 39,
  "refresh": "5s",
  "templating": {
    "list": [
      {
        "name": "namespace",
        "type": "query",
        "query": "",
        "regex": ".*",
        "allValue": ".*"
      }
    ]
  },
  "panels": [
    {
      "id": 1,
      "title": "",
      "type": "timeseries",
      "datasource": {
        "type": "prometheus",
        "uid": "prod-prometheus"
      },
      "targets": [
        {
          "refId": "A",
          "expr": "",
          "interval": "1s"
        }
      ]
    },
    {
      "id": 1,
      "title": "Broad Prometheus Query",
      "type": "timeseries",
      "fieldConfig": {
        "defaults": {}
      },
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "prometheus",
            "uid": "prod-prometheus"
          },
          "expr": "sum(rate(http_requests_total{job=~\".*\"}[10s]))"
        }
      ]
    },
    {
      "id": 3,
      "title": "Pod Logs",
      "type": "logs",
      "datasource": {
        "type": "loki",
        "uid": "prod-loki"
      },
      "targets": [
        {
          "refId": "A",
          "expr": "{namespace=~\".*\"} |= \"error\""
        }
      ]
    },
    {
      "id": 4,
      "title": "Too Many Queries",
      "type": "stat",
      "targets": [
        { "refId": "A", "expr": "up" },
        { "refId": "B", "expr": "up" },
        { "refId": "C", "expr": "up" },
        { "refId": "D", "expr": "up" },
        { "refId": "E", "expr": "up" },
        { "refId": "F", "expr": "up" },
        { "refId": "G", "expr": "up" },
        { "refId": "H", "expr": "up" },
        { "refId": "I", "expr": "up" },
        { "refId": "J", "expr": "up" },
        { "refId": "K", "expr": "up" },
        { "refId": "L", "expr": "up" },
        { "refId": "M", "expr": "up" }
      ]
    }
  ]
}
`
